### ISSUE TITLE
How and why did you get into programming? 

### ISSUE THREAD

**Issue by arthurvr** [blainsmith/ama#1]

**Comment by blainsmith** [comment]
Before I went to high school I had an interest in computers so I opted to go to the local technical high school instead of my town high school. They offered the normal trades (plumbing, carpentry, welding, etc.) and academics, but they also offered an IT option. I spent 4 years in high school learning everything like binary math, networking protocols, desktop programming, design, and website development.

I was hooked since then. The immediate satisfaction of write code in a text editor and refreshing the browser to see what I made was absolutely amazing to me. I spent the next 20 years perfecting my "trade" I chose to pursue way back in 1996.

I was even able to get my hands on my first website launch every when my Junior class redesigned our high school's website. It comes complete with a JavaScript error and all! https://www.youtube.com/watch?v=jlWMXsFNUi0
