### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [blainsmith/ama#13]

**Comment by blainsmith** [comment]
Not in a formal setting, but there are a few people that I make myself available for to help them out any way I can. One of them is actually the son of my favorite high school teacher. Both him and his son are very close friends of mine now. The son was a computer science graduate out of college, but the job he got into was more support so he never got much chance to do any development work. When he wanted try and shift into an engineering position he asked to spend a few Skype sessions together go over languages, GitHub, AWS deployments, etc. He finally shifted into an engineering job and is much happier now.

I do also coach part-time at a strength and conditioning gym. That has been really rewarding being able to help people get stronger and more confident. We cover squats, dead lifts, press, and bench press as the core drivers of strength training. From there we all teach basic gymnastics work on pull up bars and rings. I also like to spend time learning and teach Weightlifting since it is such a technical sport and it is quite a challenge to teach and train for myself.
