### ISSUE TITLE
What would you make if you had infinite time and zero distractions?

### ISSUE THREAD

**Issue by arthurvr** [blainsmith/ama#3]

**Comment by blainsmith** [comment]
I have 2 digital products I would love to build and 1 physical thing.

1. Finish and polish up my weekend hackathon project http://prdapp.com and offer native apps and a new design.
2. Get a lot of the services needed for http://oddnetworks.co in an awesome state to really start taking over the world. Most of this is hush hush for now, but more info will get released as time goes one. :wink: 
3. Since I spend so much time on a computer I value the time I get to work with my hands as well to connect with the physical world. I occasionally wrench on my [Mustang](https://instagram.com/p/ipS9DUkaxc) and [Harley](https://instagram.com/p/h6w5Eoka-C/), but I would LOVE to build a [Trophy Truck](https://www.youtube.com/watch?v=JXMyZ929lpY) from scratch to race.
