### ISSUE TITLE
What makes you a "rebel geek"?

### ISSUE THREAD

**Issue by mollikka** [blainsmith/ama#8]
And what does that term mean in general?

**Comment by blainsmith** [comment]
My old boss at Harvard University gave me that name years ago. He never thought I fit the stereotype of a software engineer because I ride a Harley, have a lot of tattoos, lift weights, etc. As a joke he started calling me that one day and the name stuck.

I just kept running with it since it ended up being unique. I use a variation of it for all of my gamer tags as well. I am **rblgk** on XBox Live, PSN, Steam, Battle.net, and League of Legends. I also have http://rebelgeeks.io as a fun, social group of bikers.
